modLoader="javafml"
loaderVersion="[40,)"
license="BSD-3-Clause"

[[mods]]
modId="chromeball"
version="${file.jarVersion}"
displayName="Chrome Ball"

# We will come back later.
credits=""
authors=["teacon","jihuayu"]
description="Best Chrome Ball Mod."

[[dependencies.chromeball]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"

[[dependencies.chromeball]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
