modLoader="javafml"
loaderVersion="[31,)"

license="BSD-3-Clause"

[[mods]]
modId="chromeball"
version="${file.jarVersion}"
displayName="Chrome Ball"

# We will come back later.
credits=""

authors=["teacon","jihuayu"]

description="Best Chrome Ball Mod."

[[dependencies.nickname]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, 1.15.4]"
    ordering="NONE"
    side="BOTH"