name: test-build
on:
  push:
    paths:
      - "src/**"
      - "build.gradle"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          chmod 777 ./gradlew
          ./gradlew build --stacktrace
